[package]
name = "library-bundler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
regex = "1.11.0"
syn = { version = "2.0.79", features = ["full"] }

