[package]
authors     = ["knrew"]
description = "A library bundler for competitive programming, mainly targeting AtCoder."
edition     = "2024"
license     = "MIT"
name        = "library-bundler"
version     = "0.1.0"

[dependencies]
anyhow = "1.0.100"
clap   = {features = ["derive"], version = "4.5.20"}
syn    = {features = ["full"], version = "2.0.79"}
